services:
  postgres:
    image: postgres:15-alpine
    container_name: review-postgres
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: review
      POSTGRES_PASSWORD: review
    volumes:
      - review-postgres-data:/var/lib/postgresql/data

volumes:
  review-postgres-data: