server:
  port: 8081

spring:
  application:
    name: review
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/review
    username: review
    password: review
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: review-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  retry:
    instances:
      geminiReviewService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - com.service.review.exception.ReviewProviderException
          - java.io.IOException
          - java.net.SocketTimeoutException
  circuitbreaker:
    instances:
      geminiReviewService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - com.service.review.exception.ReviewProviderException
          - java.io.IOException
          - java.net.SocketTimeoutException

app:
  kafka-topics:
    review:
      report-auction-review-approved: "reviews.report.auction.approved"
      report-message-review-approved: "reviews.report.auction.approved"
      auction-review-approved: "reviews.auction.approved"
      auction-review-rejected: "reviews.auction.rejected"
      qa-review-approved: "reviews.qa.approved"
      qa-review-rejected: "reviews.qa.rejected"
