CREATE SCHEMA IF NOT EXISTS review;

CREATE TABLE IF NOT EXISTS review_auction_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    context TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT pk_review_auction_context PRIMARY KEY (id),
    CONSTRAINT chk_review_auction_context_type CHECK (type IN ('CREATED', 'REPORTED'))
);

CREATE TABLE IF NOT EXISTS review_message_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    context TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT pk_review_message_context PRIMARY KEY (id),
    CONSTRAINT chk_review_message_context_type CHECK (type IN ('CREATED', 'REPORTED'))
);

CREATE TABLE IF NOT EXISTS auction_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT NOT NULL,
    seller_id UUID NOT NULL,
    approved BOOLEAN NOT NULL,
    reason VARCHAR(255),
    report_reason VARCHAR(255),
    type VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id_context BIGINT NOT NULL,
    CONSTRAINT pk_auction_reviews PRIMARY KEY (id),
    CONSTRAINT chk_auction_reviews_type CHECK (type IN ('CREATED', 'REPORTED')),
    CONSTRAINT fk_auction_reviews_context
        FOREIGN KEY (id_context)
        REFERENCES review_auction_context (id)
);

CREATE TABLE IF NOT EXISTS message_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT NOT NULL,
    seller_id UUID NOT NULL,
    id_message BIGINT NOT NULL,
    approved BOOLEAN NOT NULL,
    reason VARCHAR(255),
    report_reason VARCHAR(255),
    type VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id_context BIGINT,
    CONSTRAINT pk_message_reviews PRIMARY KEY (id),
    CONSTRAINT chk_message_reviews_type CHECK (type IN ('CREATED', 'REPORTED')),
    CONSTRAINT fk_message_reviews_context
        FOREIGN KEY (id_context)
        REFERENCES review_message_context (id)
);

